In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

data_path = '../data/raw/games_best_sellers.csv'

df = pd.read_csv(data_path)
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750 entries, 0 to 749
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   name                      750 non-null    object
 1   release_date              750 non-null    object
 2   type_review               720 non-null    object
 3   has_discount              750 non-null    int64
 4   price                     750 non-null    float64
 5   discount_percent_percent  750 non-null    float64
 6   price_whitout_discount    750 non-null    float64
 7   day_release               750 non-null    int64
 8   month_release             750 non-null    int64
 9   year_release              750 non-null    int64
dtypes: float64(3), int64(4), object(3)
memory usage: 58.7+ KB

In [ ]:
df.drop(labels=['name','release_date'],inplace=True,axis=1)
df.head()

,type_review,has_discount,price,discount_percent_percent,price_whitout_discount,day_release,month_release,year_release
0,Very Positive,0,0.0,0.0,0.0,21,8,2012
1,Very Positive,0,299.0,0.0,299.0,18,5,2026
2,Mostly Positive,1,39.9,-50.0,79.8,6,12,2024
3,Mostly Positive,0,0.0,0.0,0.0,18,1,2022
4,NaN,0,0.0,0.0,0.0,17,1,2025

In [ ]:
df_cat_features = ['type_review']
df_numerical_features = ['price','discount_percent_percent','price_whitout_discount','day_release','month_release','year_release']

imputer = SimpleImputer(strategy='most_frequent')
df_cat_imputed = imputer.fit_transform(df[df_cat_features])


df_cat_imputed_trans = pd.DataFrame(df_cat_imputed,columns=imputer.get_feature_names_out())

df.drop(df_cat_features,axis=1,inplace=True)

df_preprocessed_feature = pd.concat([df_cat_imputed_trans.reset_index(drop=True),df.reset_index(drop=True)],axis=1)

In [ ]:
onehot = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
df_onehoted = onehot.fit_transform(df_preprocessed_feature[df_cat_features])
df_preprocessed_feature.drop(df_preprocessed_feature,inplace=True,axis=1)

In [ ]:
df_onehoted_pre = pd.DataFrame(df_onehoted,columns=onehot.get_feature_names_out())
df_onehoted_pre.head()

df_categorical_preprocessed = pd.concat([df_onehoted_pre.reset_index(drop=True),df.reset_index(drop=True)],axis=1)
df_categorical_preprocessed.head()

,type_review_Mixed,type_review_Mostly Negative,type_review_Mostly Positive,type_review_Overwhelmingly Positive,type_review_Positive,type_review_Very Positive,has_discount,price,discount_percent_percent,price_whitout_discount,day_release,month_release,year_release
0,0.0,0.0,0.0,0.0,0.0,1.0,0,0.0,0.0,0.0,21,8,2012
1,0.0,0.0,0.0,0.0,0.0,1.0,0,299.0,0.0,299.0,18,5,2026
2,0.0,0.0,1.0,0.0,0.0,0.0,1,39.9,-50.0,79.8,6,12,2024
3,0.0,0.0,1.0,0.0,0.0,0.0,0,0.0,0.0,0.0,18,1,2022
4,0.0,0.0,0.0,0.0,0.0,1.0,0,0.0,0.0,0.0,17,1,2025

In [ ]:
minmax = MinMaxScaler()
df_minmax = minmax.fit_transform(df_categorical_preprocessed[df_numerical_features])
df_categorical_preprocessed.drop(df_numerical_features,inplace=True,axis=1)

In [ ]:
df_numerical_prep = pd.DataFrame(df_minmax,columns = minmax.get_feature_names_out())

In [ ]:
df_numerical_prep

,price,discount_percent_percent,price_whitout_discount,day_release,month_release,year_release
0,0.000000,1.000000,0.000000,0.666667,0.636364,0.285714
1,0.747687,1.000000,0.598120,0.566667,0.363636,0.952381
2,0.099775,0.444444,0.159632,0.166667,1.000000,0.857143
3,0.000000,1.000000,0.000000,0.566667,0.000000,0.761905
4,0.000000,1.000000,0.000000,0.533333,0.000000,0.904762
...,...,...,...,...,...,...
745,0.497624,1.000000,0.398080,0.966667,0.272727,0.952381
746,0.549887,1.000000,0.439888,0.266667,0.909091,0.190476
747,0.117504,1.000000,0.093999,0.366667,0.363636,0.761905
748,0.348337,0.666667,0.398080,0.900000,0.727273,0.809524
749,0.130008,0.611111,0.160001,0.033333,0.272727,0.952381

In [ ]:
df_numerical_prep = pd.DataFrame(df_minmax,columns = minmax.get_feature_names_out())

df_preprocessed = pd.concat([df_numerical_prep.reset_index(drop=True),df_categorical_preprocessed.reset_index(drop=True)],axis=1)

In [ ]:
df_numerical_prep = pd.DataFrame(df_minmax,columns = minmax.get_feature_names_out())

df_preprocessed = pd.concat([df_numerical_prep.reset_index(drop=True),df_categorical_preprocessed.reset_index(drop=True)],axis=1)
df_preprocessed.head()

,price,discount_percent_percent,price_whitout_discount,day_release,month_release,year_release,type_review_Mixed,type_review_Mostly Negative,type_review_Mostly Positive,type_review_Overwhelmingly Positive,type_review_Positive,type_review_Very Positive,has_discount
0,0.000000,1.000000,0.000000,0.666667,0.636364,0.285714,0.0,0.0,0.0,0.0,0.0,1.0,0
1,0.747687,1.000000,0.598120,0.566667,0.363636,0.952381,0.0,0.0,0.0,0.0,0.0,1.0,0
2,0.099775,0.444444,0.159632,0.166667,1.000000,0.857143,0.0,0.0,1.0,0.0,0.0,0.0,1
3,0.000000,1.000000,0.000000,0.566667,0.000000,0.761905,0.0,0.0,1.0,0.0,0.0,0.0,0
4,0.000000,1.000000,0.000000,0.533333,0.000000,0.904762,0.0,0.0,0.0,0.0,0.0,1.0,0

In [ ]:
if not os.path.exists('../data/raw/preprocessed'):
    os.mkdir('../data/raw/preprocessed')
    df.to_csv(os.path.join('../data/raw/preprocessed/','date_preprocessed.csv'),index=False)